### ISSUE TITLE
UnicodeError: label empty or too long

### ISSUE THREAD

**Issue by tim-moody** [learningequality/BasicCrawler#7]
```
ERROR:crawler:ERROR 404 when getting url=https://www.cdc.gov/ncbddd/spanish/actearly/milestones/photolibrary/videos/1year/language/Trata-de-imitar-las-palabras-que-escucha-508.pdf
WARNING:crawler:HEAD request failed for url https://www.cdc.gov/ncbddd/spanish/actearly/milestones/photolibrary/videos/1year/language/Trata-de-imitar-las-palabras-que-escucha-508.pdf
Traceback (most recent call last):
  File "/usr/lib/python3.8/encodings/idna.py", line 165, in encode
    raise UnicodeError("label empty or too long")
UnicodeError: label empty or too long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./scan-cdc", line 26, in <module>
    channel_tree = crawler.crawl(limit=300000)
  File "/usr/local/lib/python3.8/dist-packages/basiccrawler/crawler.py", line 312, in crawl
    verdict, head_response = self.is_media_file(original_url)
  File "/usr/local/lib/python3.8/dist-packages/basiccrawler/crawler.py", line 195, in is_media_file
    head_response = self.make_request(url, method='HEAD')
  File "/usr/local/lib/python3.8/dist-packages/basiccrawler/crawler.py", line 409, in make_request
    response = self.SESSION.request(method, url, *args, timeout=timeout, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/cachecontrol/adapter.py", line 53, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 300, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 156, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)

```

**Comment by tim-moody** [comment]
I suspect that this and the out of memory errors occur when bs4 is given something that is not html. I am working on a rewrite that looks first for html rather than media and only puts html urls on the queue. It would then do media accounting in on_page rather than the main loop.

**Comment by tim-moody** [comment]
I'd also like to add media that are in src and not just a tags. Not sure if they belong in children or a new assets list.

**Comment by ivanistheone** [comment]
> errors occur when bs4 is given something that is not html.

Yes, most likely.


>  I am working on a rewrite that looks first for html rather than media and only puts html urls on the queue.

Nice!


> I'd also like to add media that are in src and not just a tags. Not sure if they belong in children or a new assets list.

I'd put in as children to keep things simple, but maybe add some special attribute in case we want to distiguish later, e.g., `"from": "src" ` or `"from": "src-set"` etc... (I can imagine some downstream process wanting to choose only a subset of these media files depending on how they appear in the page).

**Comment by tim-moody** [comment]
does anyone use the plugable url handlers? seems like an unnecessary complication.

**Comment by ivanistheone** [comment]
> does anyone use the plugable url handlers? seems like an unnecessary complication.

They were used in this crawler: https://github.com/learningequality/sushi-chef-pradigi/blob/master/pradigi_crawlers.py#L48-L57 but now that website has completely changed so that crawler will no longer be used (dead code).

In retrospect, the set-the-handler-function-to-run-in-advance approach wasn't a very good, because one has to write too many handlers that contain repetitive code with no clear way to reuse. A class-based approach for crawling/scraping would work better for doing such do-something-special-on-this-page functionality.

Another failed approach I tried earlier was to crate special handler for different paths, e.g. `/books/{name}.html` would be recognized and sent to a "book handler" — good idea, but very few sites follow such ordered structure so in the end it wasn't very useful and I removed that feature.

So overall, I'd say if getting rid of "plugable url handlers" is helpful+simplifies the code you're working on: **green light!**
